fruits = ["apple", "banana", "cherry"]
print("Original list:", fruits)
fruits.append("mango")
print("After append:", fruits)
fruits.remove("banana")
print("After remove:", fruits)
popped = fruits.pop()
print("Popped item:", popped)
print("After pop:", fruits)
fruits.append("kiwi")
fruits.sort()
print("After sort:", fruits)
fruits.reverse()
print("After reverse:", fruits)
print("Length of list:", len(fruits))
print("Is 'apple' in list?", "apple" in fruits)